#!/usr/bin/env node
/**
 * The vision's targets (PRODUCT.md, "Vision"), measured from tables that
 * already exist. Read-only. Deliberately imports nothing from src/: it has
 * to run inside the production container by being piped to `node -`,
 * and the runtime image ships build/, not scripts/ or src/.
 *
 *   node scripts/vision-metrics.mjs [--json]           # local, DATA_DIR/results.db
 *   ssh mea 'docker exec -i <container> node --input-type=module - --json' < scripts/vision-metrics.mjs
 *
 * Generation outcomes are read from the legacy `lessons` table on purpose:
 * that is the one generation writes. lessons_v2 is unadopted and reading
 * it answers empty (src/lib/server/storage-inventory.ts).
 *
 * Autogenerated share = generation runs (lessons.at) in the last 30 days.
 * Strict: `ready` with no tutor-written lesson_materials row ('edited' or
 * 'restored'; generation never writes that table). Lenient: `ready` or `held`.
 */
import { DatabaseSync } from 'node:sqlite';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const DAY = 86_400_000;
const GATE_TARGET = 10;

const inWindow = (iso, from, to) => {
  if (!iso) return false;
  const t = new Date(iso).getTime();
  return t > from && t <= to;
};

/** 'YYYY-MM' of the calendar month before `now`, in Israel. */
function previousMonth(now) {
  const [y, m] = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jerusalem', year: 'numeric', month: '2-digit' })
    .format(now).split('-').map(Number);
  const py = m === 1 ? y - 1 : y;
  const pm = m === 1 ? 12 : m - 1;
  return `${py}-${String(pm).padStart(2, '0')}`;
}

export function measure(db, now) {
  const to = now.getTime();
  const from = to - 30 * DAY;

  const taught = db.prepare(`SELECT student_id, "end" FROM bookings_v2 WHERE status != 'cancelled'`).all();
  const activeStudents = new Set(taught.filter((b) => inWindow(b.end, from, to)).map((b) => b.student_id)).size;

  const lessonsTaught = taught.filter((b) => inWindow(b.end, from, to)).length;

  const touched = new Set(db.prepare(
    `SELECT DISTINCT lesson_slug FROM lesson_materials WHERE origin IN ('edited','restored')`).all()
    .map((r) => r.lesson_slug));
  /* A lesson copied from the prepared library ran no engine: it is not a
     generation run, so it is counted apart and kept out of the runs and
     the gate (docs/superpowers/specs/2026-09-28-prepared-library-design.md).
     The masters themselves are ordinary runs. */
  const hasUses = !!db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'library_uses'`).get();
  const copies = new Set(hasUses ? db.prepare(`SELECT lesson_slug FROM library_uses`).all().map((r) => r.lesson_slug) : []);
  let copiesInWindow = 0;

  let total = 0, strict = 0, lenient = 0;
  for (const r of db.prepare(`SELECT slug, at, status FROM lessons WHERE status IN ('ready','held','failed')`).all()) {
    if (!inWindow(r.at, from, to)) continue;
    if (copies.has(r.slug)) { copiesInWindow += 1; continue; }
    total += 1;
    if (r.status === 'ready' || r.status === 'held') lenient += 1;
    if (r.status === 'ready' && !touched.has(r.slug)) strict += 1;
  }

  const month = previousMonth(now);
  let paidAgorot = 0, owedAgorot = 0;
  for (const p of db.prepare(`SELECT date, amount_agorot, status FROM payments`).all()) {
    if (!String(p.date).startsWith(month)) continue;
    if (p.status === 'paid') paidAgorot += p.amount_agorot;
    else if (p.status === 'owed') owedAgorot += p.amount_agorot;
  }

  /* Clean = ready AND delivered. A `ready` row with a problem generated fine
     but never reached the student's page (lesson/queue.ts records that on
     `problem`); a lesson no child saw is not a clean run. */
  let streak = 0;
  const runs = db.prepare(
    `SELECT slug, status, problem FROM lessons WHERE status IN ('ready','held','failed') ORDER BY at DESC, id DESC`).all()
    .filter((r) => !copies.has(r.slug));
  for (const r of runs) { if (r.status !== 'ready' || r.problem) break; streak += 1; }

  return {
    activeStudents,
    autogen: { units: total, strict: total ? strict / total : null, lenient: total ? lenient / total : null },
    revenue: { month, paidAgorot, owedAgorot },
    coverage: { runs: total, taught: lessonsTaught },
    gate: { streak, target: GATE_TARGET },
    library: { copies: copiesInWindow },
    notes: [
      "homework has no origin column; its share is not measured separately — a `ready` lesson's homework was generated with it.",
      "a run counts as clean only if it is `ready` and reached the student's page; runs before 2026-09-25 never recorded a failed delivery, so an older `ready` may still be one.",
      "active students counts only lessons booked through the site (bookings_v2); lessons arranged outside it are not counted.",
    ],
  };
}

const pct = (x) => (x === null ? 'n/a (no generation runs in 30 days)' : `${Math.round(x * 100)}%`);
const ils = (agorot) => `₪${(agorot / 100).toLocaleString('he-IL')}`;

function main() {
  const path = process.env.DB_PATH || join(process.env.DATA_DIR ?? './data', 'results.db');
  const m = measure(new DatabaseSync(path, { readOnly: true }), new Date());
  if (process.argv.includes('--json')) { console.log(JSON.stringify(m, null, 2)); return; }
  console.log(`active students (30d)     ${m.activeStudents} / 10`);
  console.log(`autogenerated, strict     ${pct(m.autogen.strict)} / 80%   (${m.autogen.units} generation runs)`);
  console.log(`autogenerated, lenient    ${pct(m.autogen.lenient)}`);
  console.log(`from the library (30d)    ${m.library.copies} lessons, no engine run`);
  console.log(`generation runs vs lessons taught (30d)   ${m.coverage.runs} / ${m.coverage.taught}`);
  console.log(`revenue ${m.revenue.month}         paid ${ils(m.revenue.paidAgorot)} · owed ${ils(m.revenue.owedAgorot)} / ₪10,000`);
  console.log(`gate: clean runs in a row ${m.gate.streak} / ${m.gate.target}`);
  for (const n of m.notes) console.log(`note: ${n}`);
}

/* argv[1] is '-' when the script is piped to `node -` over SSH. */
const arg = process.argv[1];
if (!arg || arg === '-' || import.meta.url === pathToFileURL(arg).href) main();
