// A lesson slug becomes a URL path segment AND a directory name, so it has
// to satisfy urls.ts's allowlist. It did not.
//
// slugify kept `\p{L}` — any letter — so on a Hebrew tutoring service every
// real student's name went into the slug in Hebrew, and publish() threw
// "urls: invalid slug" on the way to disk. The lesson had already been
// generated by then: minutes of work and a slice of the engine's daily quota,
// spent and discarded. It reached production and stayed there because the
// only lesson ever generated successfully was a Latin-named test.
//
// Found by booking a real lesson against production. No unit test could have
// caught it: generateLesson and publish were each covered, and the bug lived
// in the handoff between them.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

process.env.DATA_DIR = await mkdtemp(join(tmpdir(), 'slug-'));

const { assertPathSegment } = await import('../../src/lib/server/urls.ts');
const { slugifyForTest } = await import('../../src/lib/server/lesson/queue.ts');

/** Mirrors how triggerForBooking composes a slug. */
const slugFor = (name, subject) => `${slugifyForTest(name)}-${slugifyForTest(subject)}-${Date.now().toString(36)}`;

test('a Hebrew name produces a usable slug', () => {
  // THE regression. "יובל כהן" / "מתמטיקה" is an ordinary booking here, and
  // it used to make a slug that publish() refused.
  const slug = slugFor('יובל כהן', 'מתמטיקה');
  assert.doesNotThrow(() => assertPathSegment('slug', slug), `publish() would reject ${slug}`);
  assert.match(slug, /^[a-z0-9-]+$/);
});

test('every realistic Hebrew booking survives the round trip', () => {
  const names = ['דנה', 'אלון', 'ניקול ניסימוב', 'יובל כהן', 'נוגה'];
  const subjects = ['מתמטיקה', 'פיזיקה', 'אנגלית', 'לשון'];
  for (const n of names) {
    for (const s of subjects) {
      const slug = slugFor(n, s);
      assert.doesNotThrow(() => assertPathSegment('slug', slug), `${n} / ${s} -> ${slug}`);
    }
  }
});

test('a name that transliterates to nothing still yields a legal slug', () => {
  // Emoji, punctuation, an empty field. A slug is cosmetic — the timestamp
  // carries uniqueness — so this must degrade, never throw.
  for (const odd of ['', '   ', '🎓🎒', '???', '...']) {
    const slug = slugFor(odd, odd);
    assert.doesNotThrow(() => assertPathSegment('slug', slug), `${JSON.stringify(odd)} -> ${slug}`);
  }
});

test('Latin names are unchanged', () => {
  assert.equal(slugifyForTest('Dana Cohen'), 'dana-cohen');
  assert.equal(slugifyForTest('Math'), 'math');
});

test('the slug never contains a path traversal or a separator', () => {
  for (const bad of ['../../etc/passwd', 'a/b', 'a\\b', 'a b', '..']) {
    const out = slugifyForTest(bad);
    assert.doesNotMatch(out, /[/\\.]/, `${bad} -> ${out}`);
    assert.doesNotThrow(() => assertPathSegment('slug', out));
  }
});
